spring.application.name=employee-onboarding-system
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_onboarding
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=170094ebbb506f
spring.mail.password=76db2b6cfc5d8e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=a7F9xP2mL8qR4vN6tY1wZ5kJ3hD9sC0bU7eG2nM4pX8rT6vQ1
jwt.expiration=86400000